// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VaccinationCard.Infrastructure.Persistence;

#nullable disable

namespace VaccinationCard.Infrastructure.Migrations
{
    [DbContext(typeof(VaccinationDbContext))]
    partial class VaccinationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("VaccinationCard.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_person");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nr_age_person");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("sg_gender_person");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nm_person");

                    b.HasKey("Id");

                    b.ToTable("PERSON", (string)null);
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_user");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("pwd_hash_user");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(5)")
                        .HasDefaultValue("USER")
                        .HasColumnName("sg_role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nm_user");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.Vaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_vaccination");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("DATE")
                        .HasColumnName("dt_application_vaccination");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("CHAR(5)")
                        .HasColumnName("cd_dose_vaccination");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_person");

                    b.Property<int>("VaccineId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_vaccine");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("VaccineId");

                    b.ToTable("VACCINATION", (string)null);
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.Vaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_vaccine");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_vaccine_category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nm_vaccine");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("VACCINE", (string)null);
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.VaccineCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_vaccine_category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nm_vaccine_category");

                    b.HasKey("Id");

                    b.ToTable("VACCINE_CATEGORY", (string)null);
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.Vaccination", b =>
                {
                    b.HasOne("VaccinationCard.Domain.Entities.Person", "Person")
                        .WithMany("Vaccinations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccinationCard.Domain.Entities.Vaccine", "Vaccine")
                        .WithMany()
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.Vaccine", b =>
                {
                    b.HasOne("VaccinationCard.Domain.Entities.VaccineCategory", "Category")
                        .WithMany("Vaccines")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.Person", b =>
                {
                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.VaccineCategory", b =>
                {
                    b.Navigation("Vaccines");
                });
#pragma warning restore 612, 618
        }
    }
}
